export const mockFruit = [
  {
    id: 1,
    image: 'https://www.svgrepo.com/show/312576/mango.svg',
    prixHT: 19,
    nom: 'Mangue',
    quantite: 0,
  },
  {
    id: 2,
    image: 'https://www.svgrepo.com/show/475222/raspberry.svg',
    prixHT: 9,
    nom: 'Frambroise',
    quantite: 0,
  },
  {
    id: 3,
    image: 'https://www.svgrepo.com/show/475237/banana.svg',
    prixHT: 8,
    nom: 'Banane',
    quantite: 0,
  },
  {
    id: 4,
    image: 'https://www.svgrepo.com/show/530371/apple.svg',
    prixHT: 19,
    nom: 'Pomme',
    quantite: 0,
  },
  {
    id: 5,
    image: 'https://www.svgrepo.com/show/530353/grape.svg',
    prixHT: 7,
    nom: 'Raisin',
    quantite: 0,
  },
  {
    id: 6,
    image: 'https://www.svgrepo.com/show/489698/strawberry.svg',
    prixHT: 13,
    nom: 'Fraise',
    quantite: 0,
  },
  {
    id: 7,
    image: 'https://www.svgrepo.com/show/474519/orange.svg',
    prixHT: 64,
    nom: 'Orange',
    quantite: 0,
  },
  {
    id: 8,
    image: 'https://www.svgrepo.com/show/530077/watermelon-1.svg',
    prixHT: 39,
    nom: 'Pasteque',
    quantite: 0,
  },
];
